version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: quantumult-proxy:latest
    container_name: quantumult-proxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./requests:/app/requests
    environment:
      - PORT=3000
      - LOG_LEVEL=info
      - REQUEST_TIMEOUT=30000
      - MAX_REDIRECTS=5
      - BODY_LIMIT=10mb
      - VERBOSE_LOGGING=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge 